package projectEuler;

/**
 * Date: 09-28-16
 * @author MadChemist
 *
 * Question:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * Answer:  4613732
 */
public class Problem2 {

    public static void main(String[] args) {
        int startNum = 1;
        int endNum = 4000000;
        long runningSum = 0;
        int currentNum = 0;  //start at 1
        int prevNum = startNum;   //prev num starts at 1
        int nextNum = startNum; //next num starts at 1
        /*Loop from current val to max val.*/
        while(currentNum < endNum){
            currentNum = prevNum + nextNum; //calculate current num
            prevNum = nextNum;  //assign prev to next val
            nextNum = currentNum;   //assign next val to current val
            /*Check for even value, add to running sum if even.*/
            if(currentNum % 2 == 0) {
                runningSum += currentNum;
            }
        }
        System.out.println(runningSum);
    }
}
